"""Add linked accounts and game library tables

Revision ID: f2c5dba7d4da
Revises: c3f5d7e9b2a4
Create Date: 2026-01-15 19:09:29.194800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c5dba7d4da'
down_revision: Union[str, None] = 'c3f5d7e9b2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
